### ISSUE TITLE
AttributeError: '_MainThread' object has no attribute 'additionalInfo'

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jlubcke/pytest-pycharm#6] opened 2016-09-14 13:28 UTC
INTERNALERROR>   File "/usr/local/lib/python3.5/site-packages/pytest_pycharm.py", line 23, in pytest_exception_interact
INTERNALERROR>     thread.additionalInfo.exception = (exctype, value, traceback)
INTERNALERROR> AttributeError: '_MainThread' object has no attribute 'additionalInfo'

**Comment by nick-allen** [comment] 2016-12-06 22:20
Seeing the same problem in python 3

**Comment by Sebelino** [comment] 2017-02-04 18:37
Same here:
```
INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.6/site-packages/pytest_pycharm.py", line 23, in pytest_exception_interact
INTERNALERROR>     thread.additionalInfo.exception = (exctype, value, traceback)
INTERNALERROR> AttributeError: '_MainThread' object has no attribute 'additionalInfo'
```

**Comment by Sebelino** [comment] 2017-02-05 00:26
It is apparently a packaging issue. The problem is that pip installs an older version (0.3.0) which is not compatible with newer versions of PyCharm. This happens because the newest version (0.4.0) is ignored because it is marked as being compatible with Python 2 only. Here is an excerpt of the verbose output:
```
$ pip -v install pytest-pycharm  
Collecting pytest-pycharm
[...]
    Found link https://pypi.python.org/packages/77/cd/9b1f6800846de21c4d7290243dfc834c5459e562d411fc203f2f5edae70a/pytest-pycharm-0.2.0.tar.gz#md5=758d12921f7fe33869cfddada0b42be9 (from https://pypi.python.org/simple/pytest-pycharm/), version: 0.2.0
    Found link https://pypi.python.org/packages/ab/e3/1b52aebd31ffffae09057f7cfcdf27e51445ce3e36e9de82e0fe542cbfa0/pytest-pycharm-0.3.0.tar.gz#md5=af4ee396591de26e1729ebe0b5e473f8 (from https://pypi.python.org/simple/pytest-pycharm/), version: 0.3.0
    Skipping link https://pypi.python.org/packages/d9/9d/a4cd3728eada3e3de66341ffaaf34ea4ce55c29fb5802a293045ee250e1b/pytest_pycharm-0.4.0-py2-none-any.whl#md5=90c325d8242de62b9260589f52464d88 (from https://pypi.python.org/simple/pytest-pycharm/); it is not compatible with this Python
```
As shown above, version 0.4.0 is tagged as "py2-none-any". @jlubcke Please update the [PyPi package](https://pypi.python.org/pypi/pytest-pycharm/0.4.0) to make it support Python 3 as well, or add me (Sebelino) as a PyPi package maintainer.

http://stackoverflow.com/questions/30438216/how-do-i-upload-a-universal-python-wheel-for-python-2-and-3

**Comment by jlubcke** [comment] 2017-02-07 12:25
I've added "Sebelino" as maintainer on pypi. Is the right next thing to do now to release a 0.5.0 version with the right tagging?

**Comment by Sebelino** [comment] 2017-02-07 18:48
That will not be necessary, as there has not been any change to the codebase and does not need to be. The problem was just that when the files were packaged into a .whl and uploaded to PyPi, it was incorrectly marked as being compatible with Python 2 only. You probably did something like:
```
$ python2 setup.py bdist_wheel
$ ls dist                                
pytest_pycharm-0.4.0-py2-none-any.whl
```
which created a Python2-exclusive .whl. By supplying the `--universal` flag, a .whl marked as supporting both versions will be created:
```
$ python setup.py bdist_wheel --universal
$ ls dist
pytest_pycharm-0.4.0-py2.py3-none-any.whl
```
Anyway, I have updated the PyPi package now:
```
$ twine upload dist/*
# pip3 install pytest-pycharm                           
[...]
Successfully installed pytest-pycharm-0.4.0
```

**Closed by Sebelino** 2017-02-07 18:48 UTC

**Comment by LAKSHYA3211-dev** [comment] 2021-05-18 13:10
AttributeError: 'MainThread' object has no attribute 'TaskExecution'
what is the solution?
